Repository hhyein/project_tetris, pull requests merged in 2019-05, with the labels that each got.

#13 CLN - moveblock 형식 일관성 유지
  테트리스_완성-점수처리.c
Labels: form

#14 CLN - Game_over 함수 형식 일관성 유지
  테트리스_완성-점수처리.c
Labels: form

#15 CLN - Game_win 함수 형식 일관성 유지
  테트리스_완성-점수처리.c
Labels: form

#21 CLN showblock 함수의 함수명, 변수명, 인자명 수정
  테트리스_완성-점수처리.c
Labels: name

#30 CLN showBoard 함수 함수명 수정
  테트리스_완성-점수처리.c
Labels: name

#31 CLN initial 함수 함수명 수정
  테트리스_완성-점수처리.c
Labels: name

#32 CLN detect 함수 인자명 및 함수명 수정
  테트리스_완성-점수처리.c
Labels: name

#33 CLN Show_board 형식 수정
  테트리스_완성-점수처리.c
Labels: form

#34 CLN Detect함수 형식 수정
  테트리스_완성-점수처리.c
Labels: form

#35 CLN showBlock 형식 수정
  테트리스_완성-점수처리.c
Labels: name

#37 CLN array_down 함수 형식 수정
  테트리스_완성-점수처리.c
Labels: name

#39 CLN Show_block 함수 comment(주석) 작성
  테트리스_완성-점수처리.c
Labels: comment

#40 CLN Remove_block 함수 주석 작성
  테트리스_완성-점수처리.c
Labels: comment

#41 CLN Board_Conginition 함수 주석 작성
  테트리스_완성-점수처리.c
Labels: comment

#42 CLN Array_down 함수 주석 작성
  테트리스_완성-점수처리.c
Labels: comment

#43 CLN Print_scorelevel 함수 주석 작성
  테트리스_완성-점수처리.c
Labels: comment

#44 CLN Count_score함수 주석 작성
  테트리스_완성-점수처리.c
Labels: comment

#60 SPT - cursor 기능 함수 분할
  cursor.c
  cursor.h
  테트리스_완성-점수처리.c
Labels: split

#61 SPT scorelevel 기능 함수 분할
  scorelevel.c
  scorelevel.h
  테트리스_완성-점수처리.c
Labels: split
